spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: demo-spring-boot
#    api-a-url:
#      path: /api-a-url/**
#      url: http://localhost:8080/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090


